name: Alias
main: org.openredstone.alias.Alias
version: 1.2.1
description: >
             A plugin to define simple aliases.
commands:
  alias:
    description: Manage the plugin.

permissions:
  alias.reload:
    description: Reload the alias config.
    default: op
